preset: none
risky: true
version: 7
tab-width: 4
use-tabs: true
enabled:
  - blank_line_after_namespace
  - blank_line_after_opening_tag
  - class_definition
  - compact_nullable_typehint
  - declare_equal_normalize
  - elseif
  - encoding
  - full_opening_tag
  - function_typehint_space
  - lowercase_constants
  - lowercase_keywords
  - method_argument_space_strict
  - method_visibility_required
  - new_with_braces
  - no_closing_tag
  - no_empty_statement
  - no_leading_import_slash
  - no_leading_namespace_whitespace
  - no_spaces_after_function_name
  - no_spaces_inside_parenthesis
  - no_trailing_whitespace
  - no_trailing_whitespace_in_comment
  - property_visibility_required
  - psr12_braces
  - psr4
  - return_type_declaration
  - single_blank_line_at_eof
  - single_class_element_per_statement
  - single_import_per_statement
  - single_line_after_imports
  - single_trait_insert_per_statement
  - switch_case_semicolon_to_colon
  - switch_case_space
  - unix_line_endings
  - alpha_ordered_imports
  - array_indentation
  - binary_operator_spaces
  - cast_spaces
  - concat_without_spaces
  - lowercase_static_reference
  - magic_method_casing
  - native_function_type_declaration_casing
  - no_alias_functions
  - no_short_bool_cast
  - no_unused_imports
  - no_trailing_comma_in_list_call
  - dir_constant
  - ereg_to_preg
  - include
  - is_null
  - linebreak_after_opening_tag
  - lowercase_cast
  - magic_constant_casing
  - method_separation
  - modernize_types_casting
  - native_function_casing
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_return
  - no_blank_lines_between_imports
  - no_blank_lines_between_traits
  - no_extra_block_blank_lines
  - no_extra_consecutive_blank_lines
  - no_multiline_whitespace_around_double_arrow
  - no_multiline_whitespace_before_semicolons
  - no_php4_constructor
  - no_singleline_whitespace_before_semicolons
  - no_spaces_inside_offset
  - no_spaces_outside_offset
  - no_trailing_comma_in_singleline_array
  - no_useless_else
  - no_useless_return
  - non_printable_character
  - normalize_index_brace
  - object_operator_without_whitespace
  - phpdoc_annotation_without_dot
  - phpdoc_indent
  - phpdoc_no_access
  - phpdoc_no_package
  - phpdoc_no_useless_inheritdoc
  - phpdoc_single_line_var_spacing
  - phpdoc_trim
  - phpdoc_type_to_var
  - phpdoc_types
  - semicolon_after_instruction
  - short_array_syntax
  - short_list_syntax
  - short_scalar_cast
  - single_blank_line_before_namespace
  - single_quote
  - standardize_not_equals
  - strict_comparison
  - ternary_operator_spaces
  - not_operator_with_successor_space
  - trailing_comma_in_multiline_array
  - whitespace_after_comma_in_array
  - trim_array_spaces
  - unalign_double_arrow
  - unalign_equals
  - unary_operator_spaces
finder:
  name:
    - "*.php"
