language: php

sudo: false

php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"

env:
  matrix:
    - LARAVEL_VERSION="5.7.*" ORCHESTRA_VERSION="3.7.*"
    - LARAVEL_VERSION="5.8.*" ORCHESTRA_VERSION="3.8.*"
    - LARAVEL_VERSION="6.0" ORCHESTRA_VERSION="4.0"
    - LARAVEL_VERSION="7.0" ORCHESTRA_VERSION="5.0"

matrix:
  fast_finish: true
  exclude:
    - php: "7.1"
      env: LARAVEL_VERSION="6.0" ORCHESTRA_VERSION="4.0"
    - php: "7.1"
      env: LARAVEL_VERSION="7.0" ORCHESTRA_VERSION="5.0"

before_install:
  - mkdir -p ~/artifacts
  - rm composer.lock

install:
  - travis_retry composer require php-coveralls/php-coveralls illuminate/contracts:${LARAVEL_VERSION} orchestra/testbench:${ORCHESTRA_VERSION} --dev --prefer-dist --no-interaction --no-suggest --update-with-dependencies

script: vendor/bin/phpunit --log-junit ~/artifacts/junit.xml --coverage-clover ~/artifacts/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v -x ~/artifacts/clover.xml -o ~/artifacts/coveralls.json
