language: php

sudo: false

php:
  - 7.4
  - 7.3

env:
  global: 
    - XDEBUG_MODE="coverage"
  jobs:
    - LARAVEL_VERSION="8.0" ORCHESTRA_VERSION="6.0"
    - LARAVEL_VERSION="7.0" ORCHESTRA_VERSION="5.0"
    - LARAVEL_VERSION="6.0" ORCHESTRA_VERSION="4.0"

jobs:
  fast_finish: true
  include:
    - php: 8.0
      env: LARAVEL_VERSION="8.12" ORCHESTRA_VERSION="6.0" 

before_install:
  - mkdir -p ~/artifacts
  - rm composer.lock

install:
  - travis_retry composer require php-coveralls/php-coveralls illuminate/contracts:${LARAVEL_VERSION} orchestra/testbench:${ORCHESTRA_VERSION} --dev --prefer-dist --no-interaction --no-suggest --update-with-dependencies

script: vendor/bin/phpunit --log-junit ~/artifacts/junit.xml --coverage-clover ~/artifacts/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v -x ~/artifacts/clover.xml -o ~/artifacts/coveralls.json
